export const FETCH_USERS = 'FETCH_USER';
export const NEW_USER = 'NEW_USER';
export const LOGIN = 'LOGIN';
export const REGISTRATION = 'REGISTRATION';
export const RESET_REGISTRATION_RESPONSE = "RESET_REGISTRATION_RESPONSE";
export const RESET_LOGIN_RESPONSE = "RESET_LOGIN_RESPONSE";